name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint package
        uses: aux4/lint-package-action@v1
        with:
          package_directory: package

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test package
        uses: aux4/test-package-action@v1
        with:
          package_directory: package
          test_directory: test
